import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Provider from "./lib/SessionProvider";
import Appbar from "./pages/appbar";
import ToastProvider from "./lib/ToastProvider";
import setupLocatorUI from "@locator/runtime";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (process.env.NODE_ENV === "development") {
    setupLocatorUI();
  }
  return (
    <html lang="en" className="h-full">
      <body className="h-full flex flex-col">
        <Provider>
          <ToastProvider />
          <Appbar /> {/* height-16 or fixed */}
          <main className="flex-1 overflow-y-auto bg-gray-100">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
